[package]
name = "base64-turbo"
version = "0.2.0"
edition = "2024"
rust-version = "1.89"
description = "The fastest memory-safe Base64 engine. Formally verified (Kani/MIRI). Features runtime AVX2/AVX512 detection, NEON acceleration, zero-allocation API, and robust no_std support."
license = "MIT OR Apache-2.0"
repository = "https://github.com/hacer-bark/base64-turbo"
documentation = "https://docs.rs/base64-turbo"
readme = "README.md"
authors = ["Hacer"]
keywords = ["base64", "simd", "avx512", "neon", "encoding"]
categories = ["encoding", "hardware-support", "no-std", "web-programming"]
exclude = [
    ".github",
    ".gitignore",
    "benches/results/*",
    "benches/img/*",
    "docs/*",
]

[features]
default = ["std", "simd", "neon"]
unstable = []
std = []
simd = ["std"]
neon = []

[dev-dependencies]
rand = "0.10"
criterion = { version = "0.8", features = ["html_reports"] }
base64 = "0.22"
base64-simd = "0.8"

[lints.rust]
warnings = { level = "deny", priority = -1 }
future_incompatible = { level = "deny", priority = -1 }
unused = { level = "deny", priority = -1 }
missing_docs = "deny"
missing_debug_implementations = "deny"
unreachable_pub = "deny"
unexpected_cfgs = { level = "warn", check-cfg = ['cfg(kani)'] }

[lints.clippy]
all = { level = "deny", priority = -1 }
pedantic = { level = "deny", priority = -1 }
nursery = { level = "deny", priority = -1 }
cargo = { level = "deny", priority = -1 }
unwrap_used = "deny"
expect_used = "deny"
panic = "deny"
todo = "deny"
unimplemented = "deny"
redundant_pub_crate = "allow"

[[bench]]
name = "encoding_bench"
harness = false
